# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: about
    url: '/about'
    weight: 10
  - name: 'our research group'
    parent: 'about'
    url: '/about'
    weight: 11
  - name: 'principal investigator'
    parent: 'about'
    url: '/author/filip-biljecki'
    weight: 12
  - name: 'people'
    parent: 'about'
    url: '/people'
    weight: 13
  - name: 'our seminars'
    parent: 'about'
    url: '/seminars'
    weight: 14
  - name: news
    url: '/post'
    weight: 20
  - name: publications
    url: '/publication'
    weight: 30
  - name: 'geospatial resources'
    weight: 50
  - name: 'our data+code'
    parent: 'geospatial resources'
    url: '/data-code'
    weight: 51
  - name: 'global building morphology indicators'
    parent: 'geospatial resources'
    url: '/project/gbmi/'
    weight: 52
  - name: 'roofpedia'
    parent: 'geospatial resources'
    url: '/project/roofpedia/'
    weight: 53
  - name: 'open building data'
    parent: 'geospatial resources'
    url: '/project/ogbd/'
    weight: 54
  - name: '3d city index'
    parent: 'geospatial resources'
    url: '/project/3d-city-index/'
    weight: 54
  - name: 'open data SG'
    parent: 'geospatial resources'
    url: '/post/2020/06/24/guide-for-open-urban-data-in-singapore/'
    weight: 56
  - name: join
    weight: 80
  - name: openings
    parent: join
    url: '/opportunities/vacancies'
    weight: 81
  - name: 'why us'
    parent: join
    url: '/opportunities/why-us'
    weight: 82
  - name: prospective students
    parent: join
    url: '/opportunities/phd'
    weight: 84
  - name: 'student initiated projects'
    parent: join
    url: '/opportunities/student-projects'
    weight: 85
  - name: fellowships
    parent: join
    url: '/opportunities/fellowships'
    weight: 86
  - name: contact
    url: '#contact'
    weight: 90
    